FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev=false

COPY scripts ./scripts
COPY src ./src
COPY tsconfig.json ./

ENV NODE_ENV=production

CMD ["npm", "run", "start:worker"]
